version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12  # Change to the Python version you use
    commands:
      - echo "Updating and installing system tools..."
      - yum update -y  # yum is the package manager for Amazon Linux
      - yum install -y python3 python3-devel gcc  # Install Python and build tools
      - python3 -m ensurepip  # Ensure pip is installed
      - pip3 install --upgrade pip  # Upgrade pip

  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - cd msvc-email-blacklists  # Change to the project directory
      - pip3 install -r requirements.txt  # Install development dependencies

  build:
    commands:
      - echo "Running unit tests..."
      - pytest  # Run unit tests

  post_build:
    commands:
      - echo "Building Docker image..."
      - docker build -t devil-ops .  # Build Docker image
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 911167914667.dkr.ecr.us-east-2.amazonaws.com  # Authenticate with ECR
      - echo "Tagging Docker image..."
      - docker tag devil-ops:latest 911167914667.dkr.ecr.us-east-2.amazonaws.com/devil-ops:latest  # Tag the image
      - echo "Pushing Docker image to ECR..."
      - docker push 911167914667.dkr.ecr.us-east-2.amazonaws.com/devil-ops:latest  # Push the image to ECR

artifacts:
  files:
    - "/msvc"  # Include all files as artifacts
  discard-paths: no
