version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Cambia a la versión de Python que uses
    commands:
      - echo "Actualizando e instalando herramientas del sistema..."
      - yum update -y  # yum es el gestor de Amazon Linux
      - yum install -y python3 python3-devel gcc  # Instalamos Python y herramientas de compilación
      - python3 -m ensurepip  # Aseguramos que pip esté instalado
      - pip3 install --upgrade pip
      - echo "Instalando Pipenv y habilitando venv..."
      - pip3 install pipenv  # Instalamos Pipenv usando pip

  pre_build:
    commands:
      - echo "Instalando dependencias del proyecto con Pipenv..."
      - cd msvc-email-blacklists  # Cambiamos al directorio del proyecto
      - pipenv install --dev  # Instalamos todas las dependencias, incluyendo las de desarrollo

  build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - pipenv run pytest --cov=src --cov-report=term-missing tests/  # Ejecutamos las pruebas unitarias

  post_build:
    commands:
      - echo "Limpieza posterior a la compilación completada."

artifacts:
  files:
    - "**/*"  # Incluye todos los archivos como artefactos
  discard-paths: yes
