version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 911167914667.dkr.ecr.us-east-2.amazonaws.com  # Authenticate with ECR

  build:
    commands:
      - echo "Build started on `date`"
      - cd msvc_email_blacklists  # Change to the project directory
      - echo "Building the Docker image..."
      - docker build -t devil-ops .  # Build Docker image
      - echo "Tagging Docker image..."
      - docker tag devil-ops:latest 911167914667.dkr.ecr.us-east-2.amazonaws.com/devil-ops:latest  # Tag the image

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing Docker image to ECR..."
      - docker push 911167914667.dkr.ecr.us-east-2.amazonaws.com/devil-ops:latest  # Push the image to ECR
      - echo "Writing Images Definitions file..."
      - printf '[{"name":"devilops-container","imageUri":"911167914667.dkr.ecr.us-east-2.amazonaws.com/devil-ops:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"911167914667.dkr.ecr.us-east-2.amazonaws.com/devil-ops:latest"}' > imageDetail.json
      - cat imagedefinitions.json

artifacts:
  files:
    - 'msvc_email_blacklists/**/*'  # Include all files as artifacts
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
